Fix a crash caused by unexpected keyword argument
> TypeError: Session.request() got an unexpected keyword argument 'enable_cae'

azure-keyvault-secrets==4.9.0 added an `enable_cae=True` keyword arg
that some code or other doesn't like, so we can work around the
problem by downgrading to azure-keyvault-secrets==4.8.0.